# Generated by Django 5.0.6 on 2024-05-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_book_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='category_id',
        ),
    ]
