# Generated by Django 5.0.6 on 2024-05-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_category_food_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.category'),
        ),
    ]
