# Generated by Django 5.0.6 on 2024-05-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_food_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category_id',
            new_name='category',
        ),
    ]
