# Generated by Django 5.0.6 on 2024-05-24 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_customuser_profile_image_remove_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='table',
            field=models.ForeignKey(db_column='table_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.table', to_field='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(db_column='category_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', to_field='name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(db_column='employee_username', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(db_column='food_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.food', to_field='name'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
