# Generated by Django 5.0.6 on 2024-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_order_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
