# Generated by Django 5.0.6 on 2024-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_orderitem_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id_done',
            field=models.BooleanField(default=False),
        ),
    ]
