# Generated by Django 5.0.6 on 2024-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_book_id_done'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('time', 'table'), name='unique_time_table'),
        ),
    ]
