# Generated by Django 5.0.6 on 2024-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_orderitemcook'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcook',
            name='id_done',
            field=models.BooleanField(default=False),
        ),
    ]
